# Generated by Django 3.2.13 on 2022-06-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_placeimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimage',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
