# Generated by Django 3.2.13 on 2022-06-05 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_placeimage_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['position'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
