# Generated by Django 3.2.13 on 2022-06-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('latitude', 'longitude')},
        ),
    ]
